config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :jobs
  resources :job_applications
  resources :companies

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :integer          not null, primary key
#  position    :string
#  location    :string
#  description :text
#  company_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Job < ActiveRecord::Base
  belongs_to :company
  has_many :job_applications, dependent: :destroy
  validates :company_id, presence: true
  validates :position, presence: true
  validates :description, presence: true
  validates :description, length: { minimum: 100 }
  validates :location, presence: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :set_companies_to_select, only: [:show, :new, :edit, :update, :create]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all.shuffle
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_companies_to_select
      @companies_to_select = Company.all.collect { |c| [c.name, c.id] }
    end

    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:position, :location, :description, :company_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@job.errors.count, "error") %>.
      </div>
      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.select :company_id, @companies_to_select, {include_blank: ''}%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current Openings</h1>

<table class="table">
  <thead>
    <tr>
      <th>Position</th>
      <th>Company</th>
      <th>Location</th>
      <th>Description</th>
      <th>Applicant/s</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.position %></td>
        <td><%= job.company.name %> | Co. ID: <%= job.company.id %></td>
        <td><%= job.location %></td>
        <td><%= truncate(job.description) %></td>
        <td><%= job.job_applications.count %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to('Post a Job', new_job_path, :class => 'btn btn-primary btn-md active', :role =>"button") %>
<%= link_to('View Companies', companies_path, :class => 'btn btn-default btn-md active', :role =>'button') %>
<%= link_to('View Job Applications', job_applications_path, :class => 'btn btn-default btn-md active', :role =>'button') %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @job.position %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format(@job.description) %>
</p>

<%= link_to('Edit', edit_job_path(@job), :class => 'btn btn-default btn-md active', :role =>'button') %>
<%= link_to('Back', jobs_path, :class => 'btn btn-default btn-md active', :role =>'button') %>