config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :jobs
  resources :job_applications
  resources :companies

end

app/models/job_application.rb
# == Schema Information
#
# Table name: job_applications
#
#  id           :integer          not null, primary key
#  name         :string
#  resume       :text
#  cover_letter :text
#  job_id       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  image        :string
#  remote_image :string
#  user_id      :integer
#

class JobApplication < ActiveRecord::Base
  belongs_to :job
  belongs_to :user
  has_many :technologies, dependent: :destroy
  validates :resume, presence: true
  validates :cover_letter, presence: true
  validates :job_id, presence: true
  validates :user_id, presence: true
  mount_uploader :image, AvatarUploader
  mount_uploader :remote_image, AvatarUploader
end

app/controllers/job_applications_controller.rb
class JobApplicationsController < ApplicationController
  before_action :set_job_application, only: [:show, :edit, :update, :destroy]
  before_action :set_jobs_to_select, only: [:show, :new, :edit, :update, :create]

  # GET /job_applications
  # GET /job_applications.json
  def index
    @job_applications = JobApplication.where(user: @current_user)
  end

  # GET /job_applications/1
  # GET /job_applications/1.json
  def show
  end

  # GET /job_applications/new
  def new
    @job_application = JobApplication.new
    @job_application.user = @current_user
  end

  # GET /job_applications/1/edit
  def edit
  end

  # POST /job_applications
  # POST /job_applications.json
  def create
    @job_application = JobApplication.new(job_application_params)

    respond_to do |format|
      if @job_application.save
        format.html { redirect_to @job_application, notice: 'Job application was successfully created.' }
        format.json { render :show, status: :created, location: @job_application }
      else
        format.html { render :new }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_applications/1
  # PATCH/PUT /job_applications/1.json
  def update
    respond_to do |format|
      if @job_application.update(job_application_params)
        format.html { redirect_to @job_application, notice: 'Job application was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_application }
      else
        format.html { render :edit }
        format.json { render json: @job_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_applications/1
  # DELETE /job_applications/1.json
  def destroy
    @job_application.destroy
    respond_to do |format|
      format.html { redirect_to job_applications_url, notice: 'Job application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_jobs_to_select
      @jobs_to_select = Job.all.collect { |j| [j.position, j.id] }
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_job_application
      @job_application = JobApplication.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_application_params
      params.require(:job_application).permit(:name, :resume, :cover_letter, :job_id, :image, :remote_image, :thumb, :mini, :default, :remove_image, :image_cache, :user_id, technology_ids: [])
    end
end

app/helpers/job_applications_helper.rb
module JobApplicationsHelper
end

app/views/job_applications/_form.html.erb
<%= form_for @job_application, :html => {:multipart => true} do |f| %>
  <% if @job_application.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@job_application.errors.count, "error") %>.
      </div>
      <ul>
        <% @job_application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if !@job_application.image? %>
      <%= f.label 'Upload Avatar:' %>
    <% end %>

    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %><br><br>
    <%= image_tag(@job_application.image.to_s) %><br>

    <% if @job_application.image? %>
      <%= f.label 'Remove Avatar?' %>
      <%= f.check_box :remove_image %>
    <% end %>
  </div>

  <div class="field">
    <%= f.label :resume %><br>
    <%= f.text_area :resume %>
  </div>

  <div class="field">
    <%= f.label :cover_letter %><br>
    <%= f.text_area :cover_letter %>
  </div>

  <div class="field">
    <h4>Technologies You Use:</h4>
      <%= hidden_field_tag "job_application[technology_ids][]", nil %>
      <% Technology.all.each do |technology| %>
        <%= label_tag dom_id(technology), "", class: "checkbox-inline" %>
        <%= check_box_tag "job_application[technology_ids][]", technology.id,
        @job_application.technology_ids.include?(technology.id), id: dom_id(technology) %>
        <%= technology.name %>
      <% end %>
  </div>

  <div class="field">
    <%= f.label :job_id %><br>
    <%= f.select :job_id, @jobs_to_select, {include_blank: ''}%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  <%= f.hidden_field :user_id %>
<% end %>

app/views/job_applications/edit.html.erb
<h1>Edit Your Job Application</h1>
<br><br>
<p>Upload a new avatar?</p>
<%= render 'form' %>

<%= link_to 'Show', @job_application %> |
<%= link_to 'Back', job_applications_path %>

app/views/job_applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Job Applications</h1>
<% if !signed_in? %>
  <h3>Sign in to apply!</h3>
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Avatar</th>
        <th>Name</th>
        <th>Resume</th>
        <th>Cover letter</th>
        <th>Job</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @job_applications.each do |job_application| %>
        <tr>
          <td><%= image_tag job_application.image.thumb.to_s %></td>
          <td><%= job_application.name %></td>
          <td><%= truncate(job_application.resume) %></td>
          <td><%= truncate(job_application.cover_letter) %></td>
          <td><%= job_application.job.position %> | Job Id: <%= job_application.job.id%></td>
          <td><%= link_to 'Show', job_application %></td>
          <td><%= link_to 'Edit', edit_job_application_path(job_application) %></td>
          <td><%= link_to 'Destroy', job_application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to('Apply to a Job', new_job_application_path, :class => 'btn btn-primary btn-md active', :role =>"button") %>
  <%= link_to('View Jobs', jobs_path, :class => 'btn btn-default btn-md active', :role =>'button') %>
  <%= link_to('View Companies', companies_path, :class => 'btn btn-default btn-md active', :role =>'button') %>
<% end %>

app/views/job_applications/new.html.erb
<h1>Apply to a Job</h1>
<br><br>
<%= render 'form' %>

<%= link_to 'Back', job_applications_path %>

app/views/job_applications/show.html.erb
<p id="notice"><%= notice %></p>


<p><strong>Avatar:</strong></p>
<p><%= image_tag(@job_application.image.to_s) %></p>
<br />
<p><strong>Name:</strong></p>
<%= @job_application.name %><br>

<p><strong>Resume:</strong></p>
<%= simple_format(@job_application.resume) %><br>

<p><strong>Cover letter:</strong></p>
  <%= simple_format(@job_application.cover_letter) %><br>

<p><strong>Technologies Applicant Has Used:</strong></p>
<% @job_application.technologies.each do |t| %>
  <%= t.name + " | " %>
<% end %><br>

<p><strong>Job Applying To:</strong></p>
<%= @job_application.job.position %><br><br>

<%= link_to('Edit', edit_job_application_path(@job_application), :class => 'btn btn-default btn-md active', :role =>'button') %>
<%= link_to('Back', job_applications_path, :class => 'btn btn-default btn-md active', :role =>'button') %>