config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'welcome#index'

  resources :jobs
  resources :job_applications
  resources :companies

end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id                  :integer          not null, primary key
#  name                :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  company_logo        :string
#  remote_company_logo :string
#

class Company < ActiveRecord::Base
  has_many :jobs, dependent: :destroy
  has_many :technologies, dependent: :destroy
  has_many :job_applications, through: :jobs, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  mount_uploader :company_logo, CompanyLogoUploader
  mount_uploader :remote_company_logo, CompanyLogoUploader
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all.sort
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :company_logo, :company_logo_cache, :remove_company_logo, :mini, :thumb, :default, :remote_company_logo, :remote_company_logo_cache, technology_ids: [], technology_id: [])
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for @company, :html => {:multipart => true} do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@company.errors.count, "error") %>.
      </div>
      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <% if !@company.company_logo? %>
      <%= f.label 'Upload Company Logo:' %>
    <% end %>
    <%= f.file_field :company_logo %>
    <%= f.hidden_field :company_logo_cache %>
    <%= image_tag(@company.company_logo.to_s) %>
    <br />
    <% if @company.company_logo? %>
      <%= f.label 'Remove logo?' %>
      <%= f.check_box :remove_company_logo %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label "Company Name:" %><br>
    <%= f.text_field :name %>
  </div><br>
  <h4>Technologies this company uses:</h4>
  <div class="field"
    <%= hidden_field_tag "company[technology_ids][]", nil %>
    <% Technology.all.each do |technology| %>
    <%= label_tag dom_id(technology), "", class: "checkbox-inline" %>
    <%= check_box_tag "company[technology_ids][]", technology.id,
      @company.technology_ids.include?(technology.id), id: dom_id(technology) %>
    <%= technology.name %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Your Company</h1>
<br><br>
<p>Update your logo?</p>
<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Logo</th>
      <th>Name</th>
      <th>Current Job Openings</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= image_tag company.company_logo.thumb.to_s %></td>
        <td><%= company.name %></td>
        <td><%= company.jobs.size %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to('Add a Company', new_company_path, :class => 'btn btn-primary btn-md active', :role =>"button") %>
<%= link_to('View Job Openings', jobs_path, :class => 'btn btn-default btn-md active', :role =>'button') %>

app/views/companies/new.html.erb
<h1>Add Your Company</h1>
<br><br>
<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= image_tag(@company.company_logo.to_s) %></p>
<br /><br>
<p><strong>Company:</strong></p>
<%= @company.name %><br><br>
<p><strong>Technologies used by this company:</strong></p>
<% @company.technologies.each do |t| %>
  <%= t.name + " | " %>
<% end %><br><br>


<%= link_to('Edit', edit_company_path(@company), :class => 'btn btn-default btn-md active', :role =>'button') %>
<%= link_to('Back', companies_path, :class => 'btn btn-default btn-md active', :role =>'button') %>